### ISSUE TITLE
1.18.2 mod has failed to load correctly.

### ISSUE THREAD

**Issue by spake404** [Dolphos/Sekiro-Mod-Bugs#2]
This is an error report
[crash-2023-01-24_11.52.04-fml.txt](https://github.com/Dolphos/Sekiro-Mod-Bugs/files/10486624/crash-2023-01-24_11.52.04-fml.txt)

**Comment by Dolphos** [comment]
This issue is definitely my fault, as I've forgotten to add the dependent Libraries on my mod's page.
You will find them there from now on. Thank you for reporting the problem!
